// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://piyrqbzzoyjjogulprfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpeXJxYnp6b3lqam9ndWxwcmZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNTIwMjIsImV4cCI6MjA3MTcyODAyMn0.FPVdWa4sJKhL-6kt8AjsLt05NYtW3xHzMLVdDivbWzw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});